[package]
name = "wiggle"
version = "0.1.0"
authors = ["Jakub Konka <kubkonk@jakubkonka.com>"]
edition = "2018"

[dependencies]
generate = { path = "crates/generate" }
memory = { path = "crates/memory" }

[workspace]
members = [
  "crates/generate",
  "crates/memory"
]
exclude = ["crates/WASI"]
